### ISSUE TITLE
Hello 👋

### ISSUE THREAD

**Issue by RickyHunter024** [ModernPwner/cicuta_virosa#3]
So this is a shoot in the dark but can you give the same permissions you give to the odyssey team to the unc0ver team can just make it fair between both as I believe in the freedom of choosing what JB tool you want as some people find unc0ver better the odyssey while other find odyssey better I get that it's your exploit and you are the one who makes the rules but I wish that you get my point and consider giving the unc0ver team the same permission as the odyssey team

**Comment by tolikes** [comment]
@Oliverkiller the problem is not the permits, the problem is the money ;)

**Comment by adrianjagielak** [comment]
Even though I will use odyssey I think giving permission to unc0ver teams is good because competition is good

**Comment by RickyHunter024** [comment]
Thank you people for supporting my point 😊

**Comment by Zaq14rfv** [comment]
Why do you like unc0ver? The Cydia package manager is about to become an antique!

**Comment by Zaq14rfv** [comment]
In addition, unc0ver has ads, but Odyssey has no ads. Odyssey is the best jailbreak
@coolstar

**Comment by SZCthebandit** [comment]
> Why do you like unc0ver? The Cydia package manager is about to become an antique!

Cydia may become antiquee but some of us like it for its history. Rings my bell when I see "by Jay Freeman".

**Comment by cuj** [comment]
@Zaq14rfv do you mean phone rebel when you said unc0ver ads? phone rebel actually has a good case imo.

**Comment by adrianjagielak** [comment]
@Zaq14rfv Unc0ver is not as good as Odyssey (and most of us probably never ever try it) but as history teaches us, monopolies are never good for innovation. Im sure Odyssey would be not as good if there wasnt constant threat from other jailbreaks. And for example Apple products would be much worse if it wasnt for constant threat from Google/Microsoft. Look at how bad Internet Explorer was in the '90-early '00. Its because it had monopoly on the market, there wasnt anything like it.

**Comment by adrianjagielak** [comment]
> @Zaq14rfv Unc0ver is not as good as Odyssey (and most of us probably never ever try it) but as history teaches us, monopolies are never good for innovation. Im sure Odyssey would be not as good if there wasnt constant threat from other jailbreaks. And for example Apple products would be much worse if it wasnt for constant threat from Google/Microsoft. Look at how bad Internet Explorer was in the '90-early '00. Its because it had monopoly on the market, there wasnt anything like it.

@ModernPwner

**Comment by RickyHunter024** [comment]
> Why do you like unc0ver? The Cydia package manager is about to become an antique!

I think they replied to you well and actually I prefer cydia bec I used both and found sileo buggier than cydia so yeah and btw he doesn't have that ad that will make you go crazy you know it's just one thing not like you know what website plus being a monopolist isn't good you know have u seen how many lawsuits against Apple have been made up to date and have you seen the lawsuit to Microsoft back in the day, so yeah I think both teams (unc0ver and odyssey) or any new teams if it happens should have the same permissions

**Comment by TheMasterOfMike** [comment]
Felt I, someone who’s contributed to https://ios.cfw.guide should explain why giving it to unc0ver would not be a good decision, both for moral reasons, and for quite obvious reasons.

Everything I said at https://github.com/cfw-guide/ios.cfw.guide/pull/30 mostly applies as well.

unc0ver has had a history of causing issues for users, such as users fucking their OTA’s, fucking their jailbreaks, and just general bugginess/instability, these issues have been known for a while, and no one has put in the effort to fix them. So why would you want another jailbreak made with a fuck load of issues?

unc0ver also has used a bunch of old and shittier alternatives to Odyssey’s counterparts (e.g. Substitute and Libhooker, sbingner bootstrap and Procursus, etc.)

As well, it’s important to note that giving them the exploit could give grounds for pwn to fire another false DMCA against CS’s new jailbreak (similar to what they did with Chimera13/Odyssey back in July 2020)

not even gonna bring up how pwn is racist, that’s just a shitshow I do not feel like going down.

For users who really want Cydia, you can get Cydia from Sileo directly, which is not hard to do in the first place.

If u0 team wants to use this exploit, they should have to follow the guidelines to do so, rather than get away with permission being handed to them for free.

Lastly, on the topic of a monopoly...

It really is not a monopoly if all u0 team has to do is go through some minor effort which they actually have previously done but went back on when people started forking u0 and making different versions of it, it’s just a matter of if u0 team wants to put in that small amount of effort to implement that.

As well, a monopoly is only necessarily bad when the people who lead the monopoly don’t want to innovate, except CS has been updating Chimera and Odyssey with improvements, and has been actively trying to resolve the issues that are present. Even if unc0ver was to come around it wouldn’t help CS at all really improve it, since unc0ver is worse in so many ways over Chimera/Odyssey and probably this new Odyssey14 app.

Seeing their laziness at updating unc0ver though, I doubt that will happen.

**Comment by RickyHunter024** [comment]
You convinced me
